/**
 * Emit dist/tokens.css from tokens/applied-form.tokens.json and fonts/.
 *
 * :root carries the shared core. [data-register="i"] and [data-register="ii"]
 * set the register-specific tokens. Apply the attribute at a document
 * boundary, never mid-page.
 */
import { writeFileSync, readdirSync } from 'node:fs';
import { brandInfo, version, colors, registers, chartSeries, chartSeriesOnLight, chartSeriesOnDark, fonts, typeScale, spacingScale, grid, display, floors, motion, rules, opacity, focus, states, radiusTokens, elevationTokens, tokens as rawTokens, deprecations } from '../src/lib/tokens.mjs';
import { ROOT, outDir , DIST} from '../src/lib/build-utils.mjs';

const OUT_DIR = outDir(DIST);
const FONT_DIR = `${ROOT}${brandInfo?.fontsDir ?? 'fonts/'}`;
const FONT_URL = brandInfo ? './fonts/' : '../fonts/';

const fam = (list) => list.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');

/** Map a woff2 filename to an @font-face block. */
function fontFace(file) {
  let family, weight, style;
  if (brandInfo?.fonts) {
    const f = brandInfo.fonts.find((x) => x.file === file);
    if (!f) return null;
    ({ family, weight, style } = f);
  } else {
    const m = file.match(/^(fraunces|libre-franklin|ibm-plex-mono)-(variable|\d{3})(-italic)?\.woff2$/);
    if (!m) return null;
    family = { fraunces: 'Fraunces', 'libre-franklin': 'Libre Franklin', 'ibm-plex-mono': 'IBM Plex Mono' }[m[1]];
    weight = m[2] === 'variable' ? '100 900' : m[2];
    style = m[3] ? 'italic' : 'normal';
  }
  return [
    '@font-face {',
    `  font-family: "${family}";`,
    `  font-style: ${style};`,
    `  font-weight: ${weight};`,
    '  font-display: swap;',
    `  src: url("${FONT_URL}${file}") format("woff2");`,
    '}',
  ].join('\n');
}

const rawColors = Object.fromEntries(Object.entries(rawTokens.color ?? {}).filter(([k]) => !k.startsWith('$')).map(([k, t]) => [k, t.$value]));
const lines = [];
lines.push(`/* Applied Form design system v${version} — generated by scripts/build-css.mjs. Do not edit. */`);
lines.push('');

const fontFiles = readdirSync(FONT_DIR).filter((f) => f.endsWith('.woff2')).sort();
for (const f of fontFiles) {
  const block = fontFace(f);
  if (block) lines.push(block);
}
lines.push('');

lines.push(':root {');
// Colour is emitted as the hex every browser understands, and again in its own colour space
// where that space is not sRGB. A hex cannot express a Display P3 accent at all: it clips to the
// nearest sRGB colour silently, which is the wrong answer for a system whose designer chose the
// wider one. The fallback comes first so an old browser keeps the sRGB value and a new one takes
// the second declaration.
const deprecated = Object.fromEntries(deprecations().map((d) => [d.path.split('.').pop(), d]));
for (const [name, hex] of Object.entries(colors)) lines.push(`  --af-color-${name}: ${hex};${deprecated[name] ? ` /* deprecated${deprecated[name].replacement ? `, use ${deprecated[name].replacement}` : ''}${deprecated[name].removeIn ? `, removed in ${deprecated[name].removeIn}` : ''} */` : ''}`);
for (const [name, list] of Object.entries(fonts)) lines.push(`  --af-font-${name}: ${fam(list)};`);
spacingScale.forEach((v, i) => lines.push(`  --af-space-${String(i + 1).padStart(2, '0')}: ${v}px;`));
lines.push(`  --af-grid-gutter: ${grid.gutter}px;`);
for (const [k, b] of Object.entries(grid.breakpoints)) {
  lines.push(`  --af-bp-${k}: ${b.minWidth}px;`);
  lines.push(`  --af-columns-${k}: ${b.columns};`);
  lines.push(`  --af-margin-${k}: ${b.margin}px;`);
}
lines.push(`  --af-grid-margin: ${grid.breakpoints.sm.margin}px;`);
lines.push(`  --af-grid-columns: ${grid.breakpoints.sm.columns};`);
lines.push(`  --af-display-weight-min: ${display.weightMin};`);
lines.push(`  --af-display-weight-max: ${display.weightMax};`);
lines.push(`  --af-display-opsz-above: ${display.opszAbove};`);
lines.push(`  --af-display-opsz-below: ${display.opszBelow};`);
// A system that permits radius or elevation declares the scale it permits them on, and the
// custom properties exist only for the steps it declared. A system that declares neither emits
// neither, so nothing in the component layer can reach for a value the system does not have.
for (const [name, t] of Object.entries(radiusTokens)) lines.push(`  --af-radius-${name}: ${t}px;`);
for (const [name, t] of Object.entries(elevationTokens)) lines.push(`  --af-elevation-${name}: ${t};`);
lines.push(`  --af-focus-ring: ${focus.ring}px;`);
lines.push(`  --af-focus-bar: ${focus.bar}px;`);
chartSeries.forEach((hex, i) => lines.push(`  --af-series-${i + 1}: ${hex};`));
chartSeriesOnLight.forEach((hex, i) => lines.push(`  --af-series-light-${i + 1}: ${hex};`));
chartSeriesOnDark.forEach((hex, i) => lines.push(`  --af-series-dark-${i + 1}: ${hex};`));
for (const [name, t] of Object.entries(typeScale)) {
  lines.push(`  --af-type-${name}-family: var(--af-font-${t.voice});`);
  lines.push(`  --af-type-${name}-size: ${t.size};`);
  lines.push(`  --af-type-${name}-weight: ${t.weight};`);
  lines.push(`  --af-type-${name}-leading: ${t.leading};`);
  if (t.tracking) lines.push(`  --af-type-${name}-tracking: ${t.tracking};`);
}
lines.push(`  --af-display-opsz-breakpoint: ${display.opszBreakpoint}px;`);
for (const [k, v] of Object.entries(motion.duration)) lines.push(`  --af-duration-${k}: ${v}ms;`);
for (const [k, v] of Object.entries(motion.easing)) lines.push(`  --af-easing-${k}: cubic-bezier(${v.join(', ')});`);
for (const [k, v] of Object.entries(rules)) lines.push(`  --af-rule-${k}: ${v}px;`);
for (const [k, v] of Object.entries(opacity)) lines.push(`  --af-opacity-${k}: ${v};`);
/* ---- UI state tokens (hover, active, disabled, selected, error) ---- */
for (const [group, leaves] of Object.entries(states)) {
  for (const [k, v] of Object.entries(leaves)) lines.push(`  --af-state-${group}-${k}: ${v};`);
}
/* ---- end UI state tokens ---- */
lines.push('}');
lines.push('');
// Grid margin and column count follow the breakpoint table.
for (const [k, b] of Object.entries(grid.breakpoints)) {
  if (k === 'sm') continue;
  lines.push(`@media (min-width: ${b.minWidth}px) { :root { --af-grid-margin: ${b.margin}px; --af-grid-columns: ${b.columns}; } }`);
}
lines.push('');

// Dark as a theme, not only as a register.
//
// `register.ii-dark` exists and has a reference page, but it made dark surface a *different
// document* rather than the same document on a different ground: an author had to write the page
// twice, and this repository derived the second copy by string replacement, which the engineering
// review has called brittle since 2.0. A theme is the other shape of the same palette. The viewer
// has three states, not two — an explicit choice either way, and the default, where only the
// system preference speaks — so the tokens are redefined for the preference (guarded so an
// explicit light choice still wins) and again for the explicit dark choice.
const themed = (selector) => {
  const p = registers['ii-dark'];
  if (!p) return [];
  const out = [`${selector} {`];
  for (const key of ['background', 'layer', 'text', 'accent', 'link', 'support', 'focus', 'muted', 'rule', 'positive', 'caution', 'critical', 'on-accent']) out.push(`  --af-${key}: ${p[key]};`);
  chartSeriesOnDark.forEach((hex, i) => out.push(`  --af-series-${i + 1}: ${hex};`));
  out.push('}');
  return out;
};

for (const [id, p] of Object.entries(registers)) {
  lines.push(`[data-register="${id}"] {`);
  for (const key of ['background', 'layer', 'text', 'accent', 'link', 'support', 'focus', 'muted', 'rule', 'positive', 'caution', 'critical', 'on-accent']) {
    lines.push(`  --af-${key}: ${p[key]};`);
  }
  // Chart series follow the ground, like every other colour that does. A page that names
  // --af-series-N gets the list for the ground it is actually on, rather than choosing between
  // an on-light and an on-dark list itself and being wrong the moment the theme changes.
  const seriesFor = id === 'ii-dark' ? chartSeriesOnDark : chartSeriesOnLight;
  seriesFor.forEach((hex, i) => lines.push(`  --af-series-${i + 1}: ${hex};`));
  lines.push(`  background: var(--af-background);`);
  lines.push(`  color: var(--af-text);`);
  lines.push(`  font-family: var(--af-font-text);`);
  lines.push('}');
  lines.push('');
}

lines.push('/* The dark theme: the same document, on the other ground. */');
lines.push('@media (prefers-color-scheme: dark) {');
lines.push(...themed('  [data-register="ii"]:not([data-theme="light"])').map((l) => (l.startsWith('  ') ? l : `  ${l}`)));
lines.push('}');
lines.push(...themed('[data-register="ii"][data-theme="dark"]'));
lines.push('');

lines.push(`/* Shared behaviours that hold in both registers. */`);
lines.push(`[data-register] a { color: var(--af-link); text-decoration: underline; }`);
lines.push(`[data-register] :focus-visible { outline: var(--af-focus-ring) solid var(--af-color-focus); outline-offset: 0; box-shadow: 0 0 0 calc(var(--af-focus-ring) + var(--af-focus-bar)) var(--af-color-ink); }`);
lines.push(`[data-register] [data-voice="data"], [data-register] code, [data-register] kbd, [data-register] samp, [data-register] data, [data-register] time { font-family: var(--af-font-data); }`);
lines.push(`[data-register] .af-label { font: var(--af-type-label-01-weight) var(--af-type-label-01-size)/var(--af-type-label-01-leading) var(--af-font-data); letter-spacing: var(--af-type-label-01-tracking); text-transform: uppercase; }`);
lines.push(`[data-register] .af-label .af-value { text-transform: none; letter-spacing: 0; }`);
lines.push(`[data-register] .af-table-scroll { overflow-x: auto; }`);
lines.push(`[data-register] th { font: var(--af-type-label-01-weight) var(--af-type-label-01-size)/var(--af-type-label-01-leading) var(--af-font-data); letter-spacing: var(--af-type-label-01-tracking); text-transform: uppercase; }`);
lines.push(`[data-register] figcaption { font: var(--af-type-data-02-weight) var(--af-type-data-02-size)/var(--af-type-data-02-leading) var(--af-font-data); }`);
lines.push(`[data-register] .af-data-02 { font: var(--af-type-data-02-weight) var(--af-type-data-02-size)/var(--af-type-data-02-leading) var(--af-font-data); }`);
lines.push(`  --af-measure: ${floors.maxMeasureCh}ch;`.replace(/^ {2}/, '') && `[data-register] { --af-measure: ${floors.maxMeasureCh}ch; }`);
// Wide-gamut colours, where a system declares one. Applied Form's palette is entirely sRGB, so
// this block is empty here and exists for the systems that are not.
const wide = Object.entries(rawColors)
  .filter(([, v]) => typeof v === 'object' && v.colorSpace && v.colorSpace !== 'srgb')
  .map(([name, v]) => `  --af-color-${name}: color(${v.colorSpace} ${v.components.join(' ')});`);
if (wide.length) {
  lines.push('@supports (color: color(display-p3 1 1 1)) {');
  lines.push('  :root {');
  lines.push(...wide.map((l) => `  ${l}`));
  lines.push('  }');
  lines.push('}');
}

// Typed custom properties for the values a stylesheet is most likely to get wrong. @property
// makes the browser reject a bad value rather than inherit it as a string, which turns a silent
// mistake into a visible one at the point it is written.
// --af-measure is deliberately NOT registered. A registered <length> is computed at the element
// that declares it and inherits as an absolute pixel value, so `66ch` would freeze to 66 times
// the *body* ch and then apply to display and data runs measured in their own. Registering it
// pushed the experimental page's measure from 66ch to 81ch: a typed property is the wrong tool
// for a value whose whole meaning is relative to the element that uses it.
for (const name of ['background', 'text', 'accent', 'link', 'layer']) {
  lines.push(`@property --af-${name} { syntax: "<color>"; inherits: true; initial-value: transparent; }`);
}

lines.push(`[data-register] .af-measure { max-width: var(--af-measure); }`);
// Prose takes the measure wherever it appears, not only where an author remembered the class.
//
// The ceiling used to be opt-in, and the reference pages held it at the four tested widths and
// broke it between them: at 1047px, one breakpoint short of the sixteen-column grid, a paragraph
// spanning eight columns measured 84ch. Nobody saw it because nobody measured there. Sampled
// widths found it the first time they ran, which is the argument for sampling.
lines.push(`[data-register] p, [data-register] li, [data-register] dd, [data-register] blockquote { max-width: var(--af-measure); }`);
for (const id of Object.keys(registers).filter((k) => k.startsWith('ii'))) {
  lines.push(`[data-register="${id}"] body, [data-register="${id}"] p, [data-register="${id}"] li { font-size: var(--af-type-body-01-size); line-height: var(--af-type-body-01-leading); }`);
  lines.push(`[data-register="${id}"] h2 { font: var(--af-type-heading-02-weight) var(--af-type-heading-02-size)/var(--af-type-heading-02-leading) var(--af-font-text); }`);
  lines.push(`[data-register="${id}"] h3 { font: var(--af-type-heading-03-weight) var(--af-type-heading-03-size)/var(--af-type-heading-03-leading) var(--af-font-text); }`);
}
lines.push(`[data-register="i"] p, [data-register="i"] li { font-size: var(--af-type-body-02-size); line-height: var(--af-type-body-02-leading); }`);
lines.push(`[data-register="i"] .af-display-01 { font: var(--af-type-display-01-weight) var(--af-type-display-01-size)/var(--af-type-display-01-leading) var(--af-font-display); font-variation-settings: "opsz" ${display.opszAbove}; }`);
lines.push(`[data-register="i"] .af-display-02 { font: var(--af-type-display-02-weight) var(--af-type-display-02-size)/var(--af-type-display-02-leading) var(--af-font-display); font-variation-settings: "opsz" ${display.opszBelow}; }`);
{
  // display-02 is clamp(36px, 5vw, 76px): it crosses the opsz breakpoint where 5vw reaches it.
  const m = typeScale['display-02'].size.match(/([\d.]+)vw/);
  const vwAt = m ? Math.ceil(display.opszBreakpoint / (Number(m[1]) / 100)) : null;
  if (vwAt) lines.push(`@media (min-width: ${vwAt}px) { [data-register="i"] .af-display-02 { font-variation-settings: "opsz" ${display.opszAbove}; } }`);
}
lines.push(`[data-register="i"] .af-heading-01 { font: var(--af-type-heading-01-weight) var(--af-type-heading-01-size)/var(--af-type-heading-01-leading) var(--af-font-display); font-variation-settings: "opsz" ${display.opszBelow}; }`);
lines.push(`[data-register] .af-data-01 { font: var(--af-type-data-01-weight) var(--af-type-data-01-size)/var(--af-type-data-01-leading) var(--af-font-data); }`);
lines.push(`.af-wordmark { display: inline-block; line-height: 0; }`);
lines.push(`.af-wordmark svg { height: 1em; width: auto; display: block; }`);
lines.push(`.af-wordmark .wm-form { fill: var(--af-color-terracotta); }`);
lines.push(`.af-wordmark .wm-applied { fill: currentColor; }`);
lines.push(`[data-register] .af-rule { border: 0; border-top: var(--af-rule-hairline) solid currentColor; }`);
lines.push(`[data-register] * { border-radius: var(--af-rule-radius); }`);
lines.push(`@media (prefers-reduced-motion: reduce) { [data-register] *, [data-register] *::before, [data-register] *::after { animation: none !important; transition: none !important; scroll-behavior: auto !important; } }`);
lines.push('');

writeFileSync(`${OUT_DIR}tokens.css`, lines.join('\n'));
console.log(`wrote dist/tokens.css (${lines.length} lines, ${fontFiles.length} font faces)`);
